version: "3.1"
services:

  web-frontend:
    container_name: web-frontend
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - 80:3000
    environment:
      FILE_SERVER: file-server
      FILE_SERVER_TOKEN: ${FILE_SERVER_TOKEN}
      MESSAGE_BROKER: rabbitmq
      MESSAGE_QUEUE: stage1
    links:
      - file-server
      - rabbitmq

  file-server:
    container_name: file-server
    image: mayth/simple-upload-server
    volumes:
      - file-storage:/var/root
    ports:
      - 3001:80
    command: -token ${FILE_SERVER_TOKEN} -port 80 /var/root

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-storage:/var/lib/rabbitmq/
      - rabbit-logs:/var/log/rabbitmq

volumes:
  file-storage:
  rabbit-storage:
  rabbit-logs:
